baseURL: "https://annguyen9461.github.io/"
languageCode: "en-us"
title: "Portfolio"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    # - identifier: About
    #   name: About
    #   title: About Me
    #   url: /about
    #   weight: 2
    - identifier: github
      name: Github
      title: github Link
      url: https://github.com/annguyen9461
      weight: 2
    - identifier: resume
      name: Resume
      title: resume Link
      url: /resume
      weight: 2

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Portfolio"
  description: MS Robotics @ Northwestern
  # staticPath: ""  # The path to serve the static files from
  favicon: "/headshot-modified.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only t/images/headshot-modified.pnghe css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    disableThemeToggle: true
    defaultTheme: "dark" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # When using hex codes for colors, quotations must be used along with the # sign
  color:
    textColor: "#343a40"
    secondaryTextColor: "#6c757d"
    textLinkColor: "#007bff"
    backgroundColor: "#eaedf0"
    secondaryBackgroundColor: "#64ffda1a"
    primaryColor: "#007bff"
    secondaryColor: "#f8f9fa"

    darkmode:
      textColor: "#212529"
      secondaryTextColor: "#B27092"
      textLinkColor: "#519e8a"
      backgroundColor: "#F0F7EE"
      secondaryBackgroundColor: "#212529"
      primaryColor: "#519e8a "
      secondaryColor: "#C4D7F2"

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo:  # Logo for the brand | default is the favicon variable
    # showBrandLogo: true # Show brand logo in nav bar | default is true
    brandName: "An Nguyen" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    enableSeparator: false
    menus:
      disableAbout: true
      disableExperience: true
      disableEducation: true
      disableProjects: false
      disableAchievements: true
      disableContact: true

  # Hero
  # hero:
  #   enable: false
  #   intro: "Hi, my name is"
  #   title: "An."
  #   subtitle: "I build things for the web"
  #   content: "A passionate web app developer. I tend to make use of modern web technologies to build websites that look great, feel fantastic, and function correctly."
  #   image: /images/hero.svg
  #   bottomImage:
  #     enable: true
  #   # roundImage: true # Make hero image circular | default false
  #   button:
  #     enable: true
  #     name: "Resume"
  #     url: "#"
  #     download: true
  #     newPage: false
  #   socialLinks:
  #     fontAwesomeIcons:
  #       - icon: fab fa-github
  #         url: https://example.com
  #       - icon: fab fa-x-twitter
  #         url: https://example.com
  #     customIcons:
  #       - icon: /fav.png
  #         url: "https://example.com"

  # About
  # about:
  #   enable: false
  #   title: "About Me"
  #   image: "/images/me.png"
  #   content: |-
  #     I am a software developer with a passion for web development. I have a background in computer science and mathematics, and I have a strong interest in the intersection of technology and art. I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA.

  #     I am currently working on a project that will be used to help people find the best way to get around the city.
  #   skills:
  #     enable: true
  #     title: "Here are a few technologies I've been working with recently:"
  #     items:
  #       - "HTML"
  #       - "CSS"
  #       - "JavaScript"
  #       - "React"
  #       - "Node"
  #       - "Express"

  # Experience
  # experience:
  #   enable: false
  #   # title: "Custom Name"
  #   items:
  #     - job: "Senior Software Developer"
  #       company: "Facebook"
  #       companyUrl: "https://example.com"
  #       date: "Jan 2022 - present"
  #       featuredLink:
  #         enable: true
  #         name: "View the project"
  #         url: "https://example.com"
  #       content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

  #     - job: "Software Developer"
  #       company: "Amazon"
  #       companyUrl: "https://example.com"
  #       date: "Sep 2020 - Dec 2021"
  #       featuredLink:
  #         enable: true
  #         url: "https://example.com"
  #       info:
  #         enable: true
  #         content: I worked as a software developer for more than one year in Amazon.
  #       content: |
  #         I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

  #         - Lead backend developer for a product.
  #         - Created a frontend design for a product.

  #     - job: "Junior Software Developer"
  #       company: "Apple"
  #       companyUrl: "https://example.com"
  #       date: "Jan 2020 - Aug 2020"
  #       info:
  #         enable: false
  #       featuredLink:
  #         enable: true
  #         url: "https://example.com"
  #       content: |
  #         I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

  #         - Lead backend developer for a product.
  #         - Created a frontend design for a product.

  #     - job: "UI/UX Designer"
  #       company: "Netflix"
  #       companyUrl: "https://example.com"
  #       date: "June 2017 - Nov 2019"
  #       featuredLink:
  #         enable: true
  #         url: "https://example.com"
  #       content: |
  #         I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

  #         - Lead backend developer for a product.
  #         - Created a frontend design for a product.

  #     - job: "Product Designer"
  #       company: "Google"
  #       companyUrl: "https://example.com"
  #       date: "Feb 2016 - Mar 2017"
  #       content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

  # Education
  # education:
  #   enable: false
  #   # title: "Custom Name"
  #   index: false
  #   items:
  #     - title: "Master of Business Administration"
  #       school:
  #         name: "University of California, Berkeley"
  #         url: "https://example.org"
  #       date: "2013 - 2015"
  #       GPA: "3.8 out of 5.0"
  #       content: |-
  #         Extracurricular Activities
  #           - Lorem ipsum dolor sit amet consectetur adipisicing elit.
  #           - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
  #     - title: "Bachelor of Science in Computer Science"
  #       school:
  #         name: "Massachusetts Institute of Technology"
  #         url: "https://example.org"
  #       date: "2009 - 2013"
  #       GPA: "3.9 out of 5.0"
  #       content: |-
  #         I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
  #         - [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)
  #         - Face mask detection using a single convolutional neural network.

  #         Extracurricular Activities
  #           - Lorem ipsum dolor sit amet consectetur adipisicing elit.
  #           - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
  #       featuredLink:
  #         enable: true
  #         name: "My academic record"
  #         url: "https://example.com"
  #     - title: "High School"
  #       school:
  #         name: "Thomas Jefferson High School for Science and Technology."
  #         url: "https://example.org"
  #       GPA: "4.2 out of 5.0"
  #       featuredLink:
  #         enable: true
  #         url: "https://example.com"

  # Achievements
  # achievements:
  #   enable: false
  #   # title: "Custom Name"
  #   items:
  #     - title: Google kickstart runner
  #       content: I solved all problems with optimal solution.
  #       url: https://example.com
  #       image: /images/achievment.jpg
  #     - title: Facebook Hackathon Winner
  #       content: Developed a product using Artificial Intelligence.
  #       image: /images/achievment.jpg
  #     - title: Hugo Profile
  #       content: Developed a theme and getting 1K+ downloads per month.
  #       url: "https://github.com/gurusabarish/hugo-profile"
  #       image: /images/achievment.jpg
  #     - title: Microsoft Imagine Runner
  #       content: We are developed a product which can help others.
  #     - title: Google Summer of Code
  #       content: Contributed to a open source project.
  #       url: https://example.com

  featured_projects:
    enable: true
    title: "Featured Projects"
    items:

    - title: Self-Reconfigurable Quadruped from Scratch
      content: A quadruped capable of walking, rolling, and bowling
      image: /images/projects/quad/quad.gif
      featured:
          name: Read More
          link: /quad
      badges: 
          - "C++"
          - "Python"
          - "ROS2"
          - "YOLO"
          - "CAD"
      links:
          - icon: fab fa-github
            url: https://github.com/annguyen9461/self-reconfigurable-quadruped    


    - title: The Pool-inator
      content: The Franka Emika Panda 7-DoF arm plays pool autonomously using MoveIt2 and OpenCV
      image: /images/projects/poolinator/pool.gif
      featured:
          name: Read More
          link: /poolinator
      badges:
          - "Python"
          - "ROS2 "
          - "MoveIt2"
          - "OpenCV"
      links:
          - icon: fab fa-github
            url: https://github.com/annguyen9461/poolinator
    
# projects 
  projects:
    enable: true
    title: "More Projects"
    items:

      - title: KUKA youBot Mobile Manipulation
        content: Trajectory planning and control of the youBot mobile manipulator in CoppeliaSim
        image: /images/projects/kuka/youBot.gif
        featured:
          name: Read More
          link: /kuka
        badges:
          - "Python"
          - "Trajectory Planning,"
          - "Manipulation"
          - "Feedforward Control"
        # links:
        #   - icon: fab fa-github
            # url: https://github.com/annguyen9461/
      
      - title: Clash of Hands
        content: The Allegro Hand to play rock-paper-scissors using machine learning strategies that help it get smarter with every game
        image: /images/projects/hand/hands.gif
        featured:
          name: Read More
          link: /hands
        badges:
          - "C++"
          - "Python"
          - "Computer Vision"
        links:
          - icon: fab fa-github
            url: https://github.com/rdlynx19/clash-of-hands

      - title: Pen Stealer
        content: The PincherX 100 robot grab a pen autonomously
        image: /images/projects/pen/pen.gif
        featured:
          name: Read More
          link: /pen-stealer
        badges:
          - "Python"
          - "OpenCV"
          - "Manipulation"
        # links:
        #   - icon: fab fa-github
            # url: https://github.com/annguyen9461/

      - title: Glowphonic
        content: An interactive musical instrument with touch petals, IMU-based tremolo, and reactive lighting synchronized via ESP32 and Max/MSP
        image: /images/projects/glowphonic/glow.gif
        featured:
          name: Read More
          link: /glowphonic
        badges:
          - "C++"
          - "Arduino"
          - "Max/MSP"
          - "Digital Music"
        links:
          - icon: fab fa-github
            url: https://github.com/annguyen9461/glowphonic/

      - title: Poetic Lens
        content: An AI pipeline that transforms photographs into poetry using computer vision and text generation
        image: /images/projects/poetic-lens/poem-cat.gif
        featured:
          name: Read More
          link: /poetic-lens
        badges:
          - "Python"
          - "PyTorch"
          - "Computer Vision"
          - "Generative AI"
          - "BLIP"
          - "GPT-2"
        links:
          - icon: fab fa-github
            url: https://github.com/annguyen9461/poetic-lens

      - title: Swarm Construction
        content: Autonomous bridge construction using a swarm of quadrotors (In Progress)
        image: /images/projects/construction/drone-carry-drox.gif
        featured:
          name: Read More
          link: /swarm-construction
        badges:
          - "Python"
          - "CAD"
          - "OptiTrack"
        # links:
        #   - icon: fab fa-github
        #     url: 
      

  # Contact
  # contact:
  #   enable: false
  #   # title: "Custom Name"
  #   content: My inbox is always open. Whether you have a question or just want to say hi, Iâ€™ll try my best to get back to you!
  #   btnName: Mail me
  #   btnLink: mailto:an@u.northwestern.edu
  #   # formspree:
  #   #   enable: true # `contact.email` value will be ignored
  #   #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
  #   #   emailCaption: "Enter your email address"
  #   #   messageCaption: "Enter your message here"
  #   #   messageRows: 5

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/annguyen9461
      linkedin: https://www.linkedin.com/in/an-ngn/
      email: annguyen2025@u.northwestern.edu
      # twitter: https://twitter.com
      # instagram: https://instagram.com
      # facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    socialShare: True
    readTime:
      enable: false
      content: "min read"
    scrollprogress:
      enable: true
    tags:
      openInNewTab: false

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "An Nguyen"
    pageNotFound: "Page not found"
    emailText: "Check out this site"
    social: GitHub

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
